### ISSUE TITLE
Hass add-on not working

### ISSUE THREAD

**Issue by marksmanaz** [danmed/TasmoBackupV1#101]
Only shows blank page when following web ui. Log contents are below.

2024-09-24 21:49:14,271 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-24 21:49:14,271 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-24 21:49:16,274 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24"
172.30.32.2 - - [24/Sep/2024:21:49:42 -0700] "GET / HTTP/1.1" 500 5 "http://192.168.17.99:8123/hassio/ingress/9409ee68_tasmobackup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "192.168.16.8, 172.30.32.1" 0.010 0.010 . -
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "Stack trace:"
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()"
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "#1 /var/www/html/lib/functions.inc.php(2): require_once('...')"
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "#2 /var/www/html/index.php(2): require_once('...')"
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "#3 {main}"
[24-Sep-2024 21:49:42] WARNING: [pool www] child 52 said into stderr: "  thrown in /var/www/html/lib/db.inc.php on line 24"
2024/09/24 21:49:42 [error] 51#51: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24
Stack trace:
#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()
#1 /var/www/html/lib/functions.inc.php(2): require_once('...')
#2 /var/www/html/index.php(2): require_once('...')
#3 {main}
  thrown in /var/www/html/lib/db.inc.php on line 24" while reading response header from upstream, client: 172.30.32.2, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.17.99:8123", referrer: "http://192.168.17.99:8123/hassio/ingress/9409ee68_tasmobackup"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "Stack trace:"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "#1 /var/www/html/lib/functions.inc.php(2): require_once('...')"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "#2 /var/www/html/index.php(2): require_once('...')"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "#3 {main}"
[24-Sep-2024 21:49:56] WARNING: [pool www] child 53 said into stderr: "  thrown in /var/www/html/lib/db.inc.php on line 24"
2024/09/24 21:49:56 [error] 51#51: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24
Stack trace:
#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()
#1 /var/www/html/lib/functions.inc.php(2): require_once('...')
#2 /var/www/html/index.php(2): require_once('...')
192.168.16.8 - - [24/Sep/2024:21:49:56 -0700] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-" 0.005 0.005 . -
#3 {main}
  thrown in /var/www/html/lib/db.inc.php on line 24" while reading response header from upstream, client: 192.168.16.8, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.17.99:8898"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "Stack trace:"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "#1 /var/www/html/lib/functions.inc.php(2): require_once('...')"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "#2 /var/www/html/index.php(2): require_once('...')"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "#3 {main}"
[24-Sep-2024 21:50:00] WARNING: [pool www] child 53 said into stderr: "  thrown in /var/www/html/lib/db.inc.php on line 24"
172.30.32.2 - - [24/Sep/2024:21:50:00 -0700] "GET / HTTP/1.1" 500 5 "http://192.168.17.99:8123/hassio/ingress/9409ee68_tasmobackup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "192.168.16.8, 172.30.32.1" 0.001 0.002 . -
2024/09/24 21:50:00 [error] 51#51: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24
Stack trace:
#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()
#1 /var/www/html/lib/functions.inc.php(2): require_once('...')
#2 /var/www/html/index.php(2): require_once('...')
#3 {main}
  thrown in /var/www/html/lib/db.inc.php on line 24" while reading response header from upstream, client: 172.30.32.2, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.17.99:8123", referrer: "http://192.168.17.99:8123/hassio/ingress/9409ee68_tasmobackup"
2024-09-24 21:55:55,203 WARN received SIGTERM indicating exit request
2024-09-24 21:55:55,204 INFO waiting for processes, nginx, php-fpm to die
[24-Sep-2024 21:55:55] NOTICE: Terminating ...
[24-Sep-2024 21:55:55] NOTICE: exiting, bye-bye!
2024-09-24 21:55:55,211 INFO stopped: php-fpm (exit status 0)
2024-09-24 21:55:55,229 INFO stopped: nginx (exit status 0)
2024-09-24 21:55:55,230 WARN stopped: processes (terminated by SIGTERM)
PING localhost (127.0.0.1): 56 data bytes

--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.075/0.075/0.075 ms
PING localhost (::1): 56 data bytes

--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.052/0.052/0.052 ms
Found IPv4
sed: can't read /etc/php7/conf.d/custom.ini: No such file or directory
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24
Stack trace:
#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()
#1 /var/www/html/lib/functions.inc.php(2): require_once('...')
#2 /var/www/html/upgrade.php(2): require_once('...')
#3 {main}
  thrown in /var/www/html/lib/db.inc.php on line 24
2024-09-24 21:56:42,957 INFO Set uid to user 0 succeeded
2024-09-24 21:56:42,958 INFO supervisord started with pid 7
2024-09-24 21:56:43,962 INFO spawned: 'processes' with pid 37
2024-09-24 21:56:43,965 INFO spawned: 'nginx' with pid 38
2024-09-24 21:56:43,966 INFO spawned: 'php-fpm' with pid 39
wait-for-it.sh: waiting 45 seconds for localhost:9000
[24-Sep-2024 21:56:43] NOTICE: fpm is running, pid 39
[24-Sep-2024 21:56:43] NOTICE: ready to handle connections
wait-for-it.sh: localhost:9000 is available after 1 seconds
2024-09-24 21:56:44,981 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-24 21:56:44,982 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-09-24 21:56:46,985 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24"
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "Stack trace:"
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()"
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "#1 /var/www/html/lib/functions.inc.php(2): require_once('...')"
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "#2 /var/www/html/index.php(2): require_once('...')"
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "#3 {main}"
[24-Sep-2024 21:56:47] WARNING: [pool www] child 52 said into stderr: "  thrown in /var/www/html/lib/db.inc.php on line 24"
2024/09/24 21:56:47 [error] 53#53: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: settings in /var/www/html/lib/db.inc.php:24
Stack trace:
#0 /var/www/html/lib/db.inc.php(24): PDO->prepare()
#1 /var/www/html/lib/functions.inc.php(2): require_once('...')
#2 /var/www/html/index.php(2): require_once('...')
#3 {main}
  thrown in /var/www/html/lib/db.inc.php on line 24" while reading response header from upstream, client: 172.30.32.2, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.17.99:8123", referrer: "http://192.168.17.99:8123/hassio/ingress/9409ee68_tasmobackup"
172.30.32.2 - - [24/Sep/2024:21:56:47 -0700] "GET / HTTP/1.1" 500 5 "http://192.168.17.99:8123/hassio/ingress/9409ee68_tasmobackup" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "192.168.16.8, 172.30.32.1" 0.010 0.009 . -

**Comment by aklausen** [comment]
i have the same problem, just black screen ( dark mode )

**Comment by patrickdk77** [comment]
Should be fixed in 1.06.09
