### ISSUE TITLE
 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by SirGoodenough** [danmed/TasmoBackupV1#28]
I am getting an error in the HA log most times, not all times, when triggering the backup via rest command.  The back-up is occurring, so this may be some HA thing and not yours, but it wasn't logged here so I thought I should let you know.  I see it when triggering the command from the HA service call panel.  I don't know if it is happening on my overnight backup, I will have to look.  That is called in an automation as the service so probably.
I love the add-on version and recently converted from the docker loaded version.  Thanks for your hard work getting this going!
Another complaint, how come I don't see a 'buy me a coffee' link, I'd like to send you a thank-you!

**Addon version:**  
```1.03.12```
**Addon config:**  
```
DBTYPE: sqlite
DBNAME: data/tasmobackupdb
(and the port is set to 8259)
```
**Here is the rest_command.yaml:**
```
---
  tasmoadmin_backup:
    url: http://192.168.57.67:8259/backupall.php
    method: GET
```
**HA Log text:**
```
2020-03-22 11:54:32 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 119, in async_service_handler
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 136, in async_service_handler
    _LOGGER.warning("Timeout call %s.", response.url, exc_info=1)
UnboundLocalError: local variable 'response' referenced before assignment

2020-03-22 11:55:50 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 119, in async_service_handler
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 136, in async_service_handler
    _LOGGER.warning("Timeout call %s.", response.url, exc_info=1)
UnboundLocalError: local variable 'response' referenced before assignment
Connected
```

**Comment by patrickdk77** [comment]
I can think the issue is it took longer to do the backups, than HA proxy was willing to wait.

Really a non-issue, but in this version 1.03.12, a cron job is running that handles backupall hourly, so manually calling it is not needed anymore. The only requirement is that you set in settings the backup min hours to a >0 value. So if you want daily backups set it to 23 or 24

**Comment by patrickdk77** [comment]
Oh, as for the fix, I was planning to thread the backups. The issue should only be happening if you have several offline devices, or devices in the list that are no longer around or have changes ip addresses. Threading would cause these timeouts to overlap instead of adding.

**Comment by SirGoodenough** [comment]
I have at least 1 that is off a lot.  The dryer sensor is only on while the dryer is running
I will look into the cron thing, that works from the HA add-on version as well?

**Comment by SirGoodenough** [comment]
I'm thinking about doing a YouTube about installing this as an addon this week, BTW.  
That is another reason you should set the 'coffee' link...

**Comment by patrickdk77** [comment]
the cron is now built into docker (HA add-on is using docker)

Each device that is off should only delay it 3 to 5seconds, and I think the timeout is 2min. It might just be cause backupall has no output, that is easy to fix. I have a lot of smart plugs that I don't have, but just on the shelf, so I normally get around a 30sec delay.

I'll look, I have only just learned you can even call it from inside HA as a service last week. Just sideeffects of how I did the HA intergration, it just worked mostly.

**Comment by SirGoodenough** [comment]
If it helps I call 2 backup services daily, one is yours, one is a snapshot of Ha sent to another drive on my network.  Here's the automation:
```
  ####################################################
  # Daily Back-up                                    #
  ####################################################
  - id: 3335705b-5677-42ba-98d4-8e843aaf78b8
    alias: Daily Backup
    initial_state: 'on'
    trigger:
      platform: time
      at: '6:14:56'
    action:
      - service: hassio.addon_start
        data:
          addon: ce20243c_remote_backup
      - service: rest_command.tasmoadmin_backup
```

**Comment by patrickdk77** [comment]
Ok, I added real html output for backupall and push it, should be ready in an hour or so.

The only issue I can think of is that the error says timeout, and the only way to make it use any time (it can easily backup 80 devices in 2seconds) is for offline devices taking 3seconds each.

So I think the issue likely is, it's not calling backupall.php at all. In the default configuration, the rest call cannot call it, cause the website isn't exposed externally outside of homeassistant. But on the TasmoBackup configuration page where it asks for you to select a port, if you put in 8259, it should work. Not sure if you left that at the default (disabled,empty) or if you filled it in. If it was already set, then the change I did should fix the problem for you. If not, that is the problem, cause it's only available within HA itself, via a proxy service handled by HA.

**Comment by SirGoodenough** [comment]
I did set-up the 8259 port and used it for the backupall get.  I ran it again after update to .13 and it grabbed everything except for the one that is not on, s expected.  It did frop a message in the HA log.  
Also I noticed it reports in GMT instead of the local time.  not a problem as long as I know that.
Here's the error...
```
2020-03-23 23:26:56 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 119, in async_service_handler
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 136, in async_service_handler
    _LOGGER.warning("Timeout call %s.", response.url, exc_info=1)
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by patrickdk77** [comment]
Ya those logs are generated by the homeassistant docker container, time will be whatever they setup.
I'm not seeing these errors when I do a rest_command call here, I was using 0.107.1 when I was testing. What version is your homeassistant?

Are you able to locate the matching backupall.php log line from the addon logs for the same time?

**Comment by SirGoodenough** [comment]
107.5 now.  supervisor 209.
```
2020-03-24 04:17:13,932 INFO Set uid to user 0 succeeded
2020-03-24 04:17:13,941 INFO supervisord started with pid 6
2020-03-24 04:17:14,947 INFO spawned: 'nginx' with pid 23
2020-03-24 04:17:14,954 INFO spawned: 'php-fpm' with pid 24
[24-Mar-2020 04:17:15] NOTICE: fpm is running, pid 24
[24-Mar-2020 04:17:15] NOTICE: ready to handle connections
2020-03-24 04:17:16,060 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-03-24 04:17:16,061 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
192.168.57.67 - - [24/Mar/2020:04:26:56 +0000] "GET /backupall.php HTTP/1.1" 499 0 "-" "HomeAssistant/0.107.5 aiohttp/3.6.1 Python/3.7" "-" 10.923 10.924 . -
172.30.32.2 - - [24/Mar/2020:04:28:00 +0000] "GET / HTTP/1.1" 200 32519 "http://192.168.57.67:8123/developer-tools/service" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.008 0.008 . -
172.30.32.2 - - [24/Mar/2020:04:28:00 +0000] "GET /resources/bootstrap.min.css HTTP/1.1" 200 121200 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:00 +0000] "GET /resources/datatables.min.css HTTP/1.1" 200 5359 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:00 +0000] "GET /lock-open-variant.png HTTP/1.1" 200 246 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:00 +0000] "GET /settings.png HTTP/1.1" 200 384 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:01 +0000] "GET /resources/jquery.min.js HTTP/1.1" 200 86596 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:01 +0000] "GET /resources/bootstrap.min.js HTTP/1.1" 200 37045 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:01 +0000] "GET /resources/datatables.min.js HTTP/1.1" 200 84309 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:39 +0000] "POST /listbackups.php HTTP/1.1" 200 11103 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.007 0.008 . -
172.30.32.2 - - [24/Mar/2020:04:28:40 +0000] "GET /resources/bootstrap.min.css HTTP/1.1" 200 121200 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/listbackups.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
172.30.32.2 - - [24/Mar/2020:04:28:40 +0000] "GET /resources/datatables.min.css HTTP/1.1" 200 5359 "http://192.168.57.67:8123/api/hassio_ingress/TBsDM82aEO8lzl8KzenjrUoTRW3UNovZXB-_N5bakHE/listbackups.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.000 - . -
127.0.0.1 - - [24/Mar/2020:05:08:00 +0000] "GET /backupall.php?docker=true HTTP/1.1" 200 586 "-" "Wget" "-" 0.006 0.004 . -
127.0.0.1 - - [24/Mar/2020:06:08:00 +0000] "GET /backupall.php?docker=true HTTP/1.1" 200 586 "-" "Wget" "-" 0.005 0.004 . -
```

**Comment by SirGoodenough** [comment]
Not sure how to find the addon logs

**Comment by patrickdk77** [comment]
That is interesting its giving a 499 error. Haven't heard of that one before
 Will look into that.

**Comment by patrickdk77** [comment]
499 error is the client, HA, gave up. That would explain the timeout.

Looking over your config I think it is cause you start the addon. Then request the backup. But I dont see a delay between there.

Could be it retries till nginx is running the webserver, but php isnt running yet. The nginx timeout for php is higher than HA timeout.

I would but a delay. 30sec? 10sec is should be enough for now. I'll work on adjusting the start order so php starts first and after it's ready start nginx. Might help solve it or just move the problem to another issue.

**Comment by patrickdk77** [comment]
Can you give this development version a try:
this will be a new add-on

https://github.com/patrickdk77/TasmoBackupV1

**Comment by SirGoodenough** [comment]
I installed the test version and stopped the released version, updated the devices and saved them, then pulled a plug out of the wall and rn the service called rest command.
after a few seconn delay got an errot.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 119, in async_service_handler
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 136, in async_service_handler
    _LOGGER.warning("Timeout call %s.", response.url, exc_info=1)
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by SirGoodenough** [comment]
I'll repeat the rest command shortly.

**Comment by SirGoodenough** [comment]
I let it sit a few minutes and the error popped again:
```
2020-03-26 11:07:08 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 119, in async_service_handler
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/usr/local/lib/python3.7/site-packages/aiohttp/helpers.py", line 586, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1257, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/rest_command/__init__.py", line 136, in async_service_handler
    _LOGGER.warning("Timeout call %s.", response.url, exc_info=1)
UnboundLocalError: local variable 'response' referenced before assignment
```

**Comment by SirGoodenough** [comment]
This is the log in the addon:
```
2020-03-26 15:55:00,372 INFO Set uid to user 0 succeeded
2020-03-26 15:55:00,380 INFO supervisord started with pid 6
2020-03-26 15:55:01,385 INFO spawned: 'processes' with pid 25
2020-03-26 15:55:01,391 INFO spawned: 'nginx' with pid 26
2020-03-26 15:55:01,399 INFO spawned: 'php-fpm' with pid 27
wait-for-it.sh: waiting 45 seconds for localhost:9000
[26-Mar-2020 15:55:01] NOTICE: fpm is running, pid 27
[26-Mar-2020 15:55:01] NOTICE: ready to handle connections
wait-for-it.sh: localhost:9000 is available after 1 seconds
2020-03-26 15:55:02,440 INFO success: processes entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-03-26 15:55:02,440 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-03-26 15:55:04,443 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
172.30.32.2 - - [26/Mar/2020:15:55:29 +0000] "GET / HTTP/1.1" 200 4176 "http://192.168.57.67:8123/config/server_control" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.015 0.012 . -
172.30.32.2 - - [26/Mar/2020:15:56:03 +0000] "POST /scan.php HTTP/1.1" 200 9092 "http://192.168.57.67:8123/api/hassio_ingress/y6Ch_atmiX3cfXB6G4W9NpAM0le7tRr_tnEcQ9tWPgE/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 26.010 26.006 . -
172.30.32.2 - - [26/Mar/2020:15:56:53 +0000] "POST /index.php HTTP/1.1" 200 37642 "http://192.168.57.67:8123/api/hassio_ingress/y6Ch_atmiX3cfXB6G4W9NpAM0le7tRr_tnEcQ9tWPgE/scan.php" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 43.545 43.545 . -
192.168.57.67 - - [26/Mar/2020:15:58:10 +0000] "GET /backupall.php HTTP/1.1" 499 0 "-" "HomeAssistant/0.107.5 aiohttp/3.6.1 Python/3.7" "-" 10.657 10.655 . -
172.30.32.2 - - [26/Mar/2020:16:03:31 +0000] "GET / HTTP/1.1" 200 36613 "http://192.168.57.67:8123/328b9854_tasmobackup" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0" "192.168.57.233, 172.30.32.1" 0.007 0.008 . -
192.168.57.67 - - [26/Mar/2020:16:07:08 +0000] "GET /backupall.php HTTP/1.1" 499 0 "-" "HomeAssistant/0.107.5 aiohttp/3.6.1 Python/3.7" "-" 10.409 10.407 . -
127.0.0.1 - - [26/Mar/2020:16:08:00 +0000] "GET /backupall.php?docker=true HTTP/1.1" 200 586 "-" "Wget" "-" 0.005 0.008 . -
```
